### ISSUE TITLE
Generate Names for World Class Security Bugs

### ISSUE THREAD

**Issue by jsbueno** [rbanffy/nsaname#9]
2018 starts showing we have a strong demand for nicely named systemic flaws - afer the past "Heartbleed" and so.

So far they could come up with "Meltdown" and "Spectre", but at current pace, the name generation for this class of security issues could be bottle-necked by not finding appropriate names as early as next week. 
"nsaname" could come to the rescue if there was an option for naming those as well.

**Comment by rbanffy** [comment]
We should start a "bugname" project similar to this.
